/**
 * Syncs deployed contract artifacts to the frontend.
 * Mirrors proofOfShip/vibecheck/smartContracts/sync-data.js
 */
const fs = require("fs");
const path = require("path");

const FRONTEND_DIR = path.join(__dirname, "../lib/contracts");
const DEPLOYMENTS_ROOT = path.join(__dirname, "../smartContracts/deployments");

const NETWORK_PRIORITY = ["celo"];

const CONTRACTS_TO_SYNC = [
  "PredictionManager",
  "RewardTreasury",
  "PointsManager",
  "SpinRewardManager",
];

if (!fs.existsSync(FRONTEND_DIR)) {
  fs.mkdirSync(FRONTEND_DIR, { recursive: true });
}

function sync() {
  console.log("--- Syncing Artifacts (Multi-network) ---");

  if (!fs.existsSync(DEPLOYMENTS_ROOT)) {
    console.warn("No deployments directory found at", DEPLOYMENTS_ROOT);
    process.exit(1);
  }

  let multiAddresses = {};
  const abis = {};
  const syncedNetworks = [];

  const existingAddressesFile = path.join(FRONTEND_DIR, "addresses.json");
  if (fs.existsSync(existingAddressesFile)) {
    try {
      multiAddresses = JSON.parse(fs.readFileSync(existingAddressesFile, "utf8"));
    } catch {
      console.warn("Could not parse existing addresses.json");
    }
  }

  for (const net of NETWORK_PRIORITY) {
    const networkDir = path.join(DEPLOYMENTS_ROOT, net);
    if (!fs.existsSync(networkDir)) {
      console.warn(`  Skipping ${net}: Directory not found.`);
      continue;
    }

    const chainIdFile = path.join(networkDir, ".chainId");
    if (!fs.existsSync(chainIdFile)) {
      console.warn(`  Skipping ${net}: .chainId not found.`);
      continue;
    }

    const chainId = fs.readFileSync(chainIdFile, "utf8").trim();
    syncedNetworks.push({ name: net, chainId });

    CONTRACTS_TO_SYNC.forEach((name) => {
      const filePath = path.join(networkDir, `${name}.json`);
      if (fs.existsSync(filePath)) {
        const data = JSON.parse(fs.readFileSync(filePath, "utf8"));

        if (!multiAddresses[name]) multiAddresses[name] = {};
        multiAddresses[name][chainId] = data.address;

        if (!abis[name]) {
          abis[name] = data.abi;
          console.log(`  Extracted ABI for ${name} from ${net}`);
        }

        console.log(`  [${net}] ${name} @ ${data.address}`);
      }
    });
  }

  if (syncedNetworks.length === 0) {
    console.error("No valid deployments found.");
    process.exit(1);
  }

  fs.writeFileSync(
    path.join(FRONTEND_DIR, "addresses.json"),
    JSON.stringify(multiAddresses, null, 2)
  );

  fs.writeFileSync(
    path.join(FRONTEND_DIR, "abis.json"),
    JSON.stringify(abis, null, 2)
  );

  const tsContent = `/**
 * Generated by scripts/sync-data.js — DO NOT EDIT MANUALLY.
 * Networks: ${syncedNetworks.map((n) => `${n.name} (${n.chainId})`).join(", ")}
 */

import addresses from './addresses.json';
import abis from './abis.json';
import type { Address } from '@/types';

export const CONTRACTS = {
  PredictionManager: {
    address: addresses.PredictionManager[42220] as Address,
    abi: abis.PredictionManager,
  },
  RewardTreasury: {
    address: addresses.RewardTreasury[42220] as Address,
    abi: abis.RewardTreasury,
  },
  PointsManager: {
    address: addresses.PointsManager[42220] as Address,
    abi: abis.PointsManager,
  },
  SpinRewardManager: {
    address: addresses.SpinRewardManager[42220] as Address,
    abi: abis.SpinRewardManager,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
`;

  fs.writeFileSync(path.join(FRONTEND_DIR, "index.ts"), tsContent);

  console.log("\n--- Sync Complete ---");
  console.log("Networks synced:", syncedNetworks.map((n) => n.name).join(", "));
}

sync();
