const fs = require("fs");
const path = require("path");

const FRONTEND_DIR = path.join(__dirname, "../ui/lib/contracts");
const DEPLOYMENTS_ROOT = path.join(__dirname, "deployments");

/** Celo mainnet only. */
const NETWORK_PRIORITY = ["celo"];
const MAINNET_CHAIN_ID = "42220";

const CONTRACTS_TO_SYNC = [
  "RewardTreasury",
  "PointsManager",
  "ActivityRegistry",
  "SpinRewardManager",
];

if (!fs.existsSync(FRONTEND_DIR)) {
  fs.mkdirSync(FRONTEND_DIR, { recursive: true });
}

function sync() {
  console.log("--- Syncing Artifacts (Celo mainnet) ---");

  if (!fs.existsSync(DEPLOYMENTS_ROOT)) {
    console.warn("No deployments directory found at", DEPLOYMENTS_ROOT);
    process.exit(1);
  }

  let multiAddresses = {};
  const abis = {};
  const syncedNetworks = [];

  const existingAddressesFile = path.join(FRONTEND_DIR, "addresses.json");
  if (fs.existsSync(existingAddressesFile)) {
    try {
      multiAddresses = JSON.parse(fs.readFileSync(existingAddressesFile, "utf8"));
    } catch {
      console.warn("Could not parse existing addresses.json");
    }
  }

  // Strip legacy testnet keys from addresses map.
  for (const name of Object.keys(multiAddresses)) {
    if (multiAddresses[name] && typeof multiAddresses[name] === "object") {
      delete multiAddresses[name]["11142220"];
    }
  }

  for (const net of NETWORK_PRIORITY) {
    const networkDir = path.join(DEPLOYMENTS_ROOT, net);
    if (!fs.existsSync(networkDir)) {
      console.warn(`  Skipping ${net}: Directory not found (deploy to mainnet first).`);
      continue;
    }

    const chainIdFile = path.join(networkDir, ".chainId");
    if (!fs.existsSync(chainIdFile)) {
      console.warn(`  Skipping ${net}: .chainId not found.`);
      continue;
    }

    const chainId = fs.readFileSync(chainIdFile, "utf8").trim();
    if (chainId !== MAINNET_CHAIN_ID) {
      console.warn(`  Skipping ${net}: expected chainId ${MAINNET_CHAIN_ID}, got ${chainId}`);
      continue;
    }

    syncedNetworks.push({ name: net, chainId });

    CONTRACTS_TO_SYNC.forEach((name) => {
      const filePath = path.join(networkDir, `${name}.json`);
      if (fs.existsSync(filePath)) {
        const data = JSON.parse(fs.readFileSync(filePath, "utf8"));

        if (!multiAddresses[name]) multiAddresses[name] = {};
        multiAddresses[name][chainId] = data.address;

        if (!abis[name]) {
          abis[name] = data.abi;
          console.log(`  Extracted ABI for ${name} from ${net}`);
        }

        console.log(`  [${net}] ${name} @ ${data.address}`);
      }
    });
  }

  // Keep ABIs from existing abis.json if no fresh deploy yet.
  const existingAbisFile = path.join(FRONTEND_DIR, "abis.json");
  if (Object.keys(abis).length === 0 && fs.existsSync(existingAbisFile)) {
    Object.assign(abis, JSON.parse(fs.readFileSync(existingAbisFile, "utf8")));
    console.log("  Reusing existing ABIs (no mainnet deployment folder yet).");
  }

  fs.writeFileSync(
    path.join(FRONTEND_DIR, "addresses.json"),
    JSON.stringify(multiAddresses, null, 2)
  );

  if (Object.keys(abis).length > 0) {
    fs.writeFileSync(path.join(FRONTEND_DIR, "abis.json"), JSON.stringify(abis, null, 2));
  }

  const addr = (name) =>
    `addresses.${name}?.[${MAINNET_CHAIN_ID}] as Address ?? ("0x0000000000000000000000000000000000000000" as Address)`;

  const tsContent = `/**
 * Generated by smartContracts/sync-data.js — prefer regenerating after mainnet deploy.
 * Network: Celo mainnet (${MAINNET_CHAIN_ID})
 */

import addresses from "./addresses.json";
import abis from "./abis.json";
import type { Address } from "@/types";
import { ZERO_ADDRESS } from "@/config/constants";

const MAINNET = "${MAINNET_CHAIN_ID}";

function mainnetAddress(map: Record<string, string> | undefined): Address {
  const addr = map?.[MAINNET];
  return (addr && addr.startsWith("0x") ? addr : ZERO_ADDRESS) as Address;
}

function envOr(map: Record<string, string> | undefined, envKey: string): Address {
  const fromEnv = process.env[envKey]?.trim();
  if (fromEnv && fromEnv.startsWith("0x") && fromEnv.length === 42) {
    return fromEnv as Address;
  }
  return mainnetAddress(map);
}

export const CONTRACTS = {
  RewardTreasury: {
    address: envOr(addresses.RewardTreasury as Record<string, string>, "NEXT_PUBLIC_REWARD_TREASURY_ADDRESS"),
    abi: abis.RewardTreasury,
  },
  PointsManager: {
    address: envOr(addresses.PointsManager as Record<string, string>, "NEXT_PUBLIC_POINTS_MANAGER_ADDRESS"),
    abi: abis.PointsManager,
  },
  ActivityRegistry: {
    address: envOr(addresses.ActivityRegistry as Record<string, string>, "NEXT_PUBLIC_ACTIVITY_REGISTRY_ADDRESS"),
    abi: abis.ActivityRegistry,
  },
  SpinRewardManager: {
    address: envOr(addresses.SpinRewardManager as Record<string, string>, "NEXT_PUBLIC_SPIN_REWARD_MANAGER_ADDRESS"),
    abi: abis.SpinRewardManager,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
`;

  // Hand-maintained index.ts is preferred over overwriting with fragile template —
  // only write addresses + abis here. Frontend index.ts is updated in the wiring commit.
  void tsContent;
  void addr;

  console.log("\n--- Sync Complete ---");
  console.log(
    "Networks synced:",
    syncedNetworks.length ? syncedNetworks.map((n) => n.name).join(", ") : "(none yet — deploy-mainnet first)"
  );
}

sync();
