/**
 * Placeholder contract registry.
 * Generated by scripts/sync-data.js after deployment — DO NOT EDIT MANUALLY.
 * Run `npm run contracts:sync` from smartContracts after deploy.
 */

import addresses from "./addresses.json";
import abis from "./abis.json";
import type { Address } from "@/types";

const CELO_CHAIN_ID = "42220";

export const CONTRACTS = {
  PredictionManager: {
    address: (addresses as Record<string, Record<string, string>>).PredictionManager?.[
      CELO_CHAIN_ID
    ] as Address | undefined,
    abi: (abis as Record<string, unknown>).PredictionManager ?? [],
  },
  RewardTreasury: {
    address: (addresses as Record<string, Record<string, string>>).RewardTreasury?.[
      CELO_CHAIN_ID
    ] as Address | undefined,
    abi: (abis as Record<string, unknown>).RewardTreasury ?? [],
  },
  PointsManager: {
    address: (addresses as Record<string, Record<string, string>>).PointsManager?.[
      CELO_CHAIN_ID
    ] as Address | undefined,
    abi: (abis as Record<string, unknown>).PointsManager ?? [],
  },
  SpinRewardManager: {
    address: (addresses as Record<string, Record<string, string>>).SpinRewardManager?.[
      CELO_CHAIN_ID
    ] as Address | undefined,
    abi: (abis as Record<string, unknown>).SpinRewardManager ?? [],
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
