/**
 * Generated by scripts/sync-data.js — DO NOT EDIT MANUALLY.
 * Networks: celo (42220), sepolia (11142220)
 */

import addresses from './addresses.json';
import abis from './abis.json';
import type { Address } from '@/types';

export const CONTRACTS = {
  RewardTreasury: {
    address: addresses.RewardTreasury[42220] as Address,
    abi: abis.RewardTreasury,
  },
  PointsManager: {
    address: addresses.PointsManager[42220] as Address,
    abi: abis.PointsManager,
  },
  ActivityRegistry: {
    address: addresses.ActivityRegistry[42220] as Address,
    abi: abis.ActivityRegistry,
  },
  SpinRewardManager: {
    address: addresses.SpinRewardManager[42220] as Address,
    abi: abis.SpinRewardManager,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
